--[[
--	AUTOCOMMAND MODULE FOR NEORG
--	This module exposes functionality for subscribing to autocommands and performing actions based on those autocommands
--]]

require('neorg.modules.base')
require('neorg.events')

local module = neorg.modules.create("core.autocommands")

function _neorg_module_autocommand_triggered(name)
	neorg.events.broadcast_event(module, neorg.events.create(module, name))
end

module.autocmd_base = function(name) return neorg.events.create_default_event(module, "core.autocommands.events." .. name) end

module.public = {

	-- @Summary Enable an autocommand event
	-- @Description By default, all autocommands are disabled for performance reasons. To enable them, use this command
	-- @Param  autocmd (string) - the relative name of the autocommand to enable
	enable_autocommand = function(autocmd)
		autocmd = autocmd:lower()
		local subscribed_autocommand = module.events.subscribed["core.autocommands"][autocmd]

		if subscribed_autocommand ~= nil then
			if subscribed_autocommand == false then
				-- Change to *.org and *.norg
				vim.cmd("autocmd " .. autocmd .. " * :lua _neorg_module_autocommand_triggered(\"core.autocommands.events." .. autocmd .. "\")")
				subscribed_autocommand = true
			end
		end
	end

}

module.events.subscribed = {

	["core.autocommands"] = {

		bufadd = false,
		bufdelete = false,
		bufenter = false,
		buffilepost = false,
		buffilepre = false,
		bufhidden = false,
		bufleave = false,
		bufmodifiedset = false,
		bufnew = false,
		bufnewfile = false,
		bufread = false,
		bufreadcmd = false,
		bufreadpre = false,
		bufunload = false,
		bufwinenter = false,
		bufwinleave = false,
		bufwipeout = false,
		bufwrite = false,
		bufwritecmd = false,
		bufwritepost = false,
		chaninfo = false,
		chanopen = false,
		cmdundefined = false,
		cmdlinechanged = false,
		cmdlineenter = false,
		cmdlineleave = false,
		cmdwinenter = false,
		cmdwinleave = false,
		colorscheme = false,
		colorschemepre = false,
		completechanged = false,
		completedonepre = false,
		completedone = false,
		cursorhold = false,
		cursorholdi = false,
		cursormoved = false,
		cursormovedi = false,
		diffupdated = false,
		dirchanged = false,
		fileappendcmd = false,
		fileappendpost = false,
		fileappendpre = false,
		filechangedro = false,
		exitpre = false,
		filechangedshell = false,
		filechangedshellpost = false,
		filereadcmd = false,
		filereadpost = false,
		filereadpre = false,
		filetype = false,
		filewritecmd = false,
		filewritepost = false,
		filewritepre = false,
		filterreadpost = false,
		filterreadpre = false,
		filterwritepost = false,
		filterwritepre = false,
		focusgained = false,
		focuslost = false,
		funcundefined = false,
		uienter = false,
		uileave = false,
		insertchange = false,
		insertcharpre = false,
		textyankpost = false,
		insertenter = false,
		insertleavepre = false,
		insertleave = false,
		menupopup = false,
		optionset = false,
		quickfixcmdpre = false,
		quickfixcmdpost = false,
		quitpre = false,
		remotereply = false,
		sessionloadpost = false,
		shellcmdpost = false,
		signal = false,
		shellfilterpost = false,
		sourcepre = false,
		sourcepost = false,
		sourcecmd = false,
		spellfilemissing = false,
		stdinreadpost = false,
		stdinreadpre = false,
		swapexists = false,
		syntax = false,
		tabenter = false,
		tableave = false,
		tabnew = false,
		tabnewentered = false,
		tabclosed = false,
		termopen = false,
		termenter = false,
		termleave = false,
		termclose = false,
		termresponse = false,
		textchanged = false,
		textchangedi = false,
		textchangedp = false,
		user = false,
		usergettingbored = false,
		vimenter = false,
		vimleave = false,
		vimleavepre = false,
		vimresized = false,
		vimresume = false,
		vimsuspend = false,
		winclosed = false,
		winenter = false,
		winleave = false,
		winnew = false,
		winscrolled = false

	}
}

module.events.defined = {

	bufadd = module.autocmd_base("bufadd"),
	bufdelete = module.autocmd_base("bufdelete"),
	bufenter = module.autocmd_base("bufenter"),
	buffilepost = module.autocmd_base("buffilepost"),
	buffilepre = module.autocmd_base("buffilepre"),
	bufhidden = module.autocmd_base("bufhidden"),
	bufleave = module.autocmd_base("bufleave"),
	bufmodifiedset = module.autocmd_base("bufmodifiedset"),
	bufnew = module.autocmd_base("bufnew"),
	bufnewfile = module.autocmd_base("bufnewfile"),
	bufread = module.autocmd_base("bufread"),
	bufreadcmd = module.autocmd_base("bufreadcmd"),
	bufreadpre = module.autocmd_base("bufreadpre"),
	bufunload = module.autocmd_base("bufunload"),
	bufwinenter = module.autocmd_base("bufwinenter"),
	bufwinleave = module.autocmd_base("bufwinleave"),
	bufwipeout = module.autocmd_base("bufwipeout"),
	bufwrite = module.autocmd_base("bufwrite"),
	bufwritecmd = module.autocmd_base("bufwritecmd"),
	bufwritepost = module.autocmd_base("bufwritepost"),
	chaninfo = module.autocmd_base("chaninfo"),
	chanopen = module.autocmd_base("chanopen"),
	cmdundefined = module.autocmd_base("cmdundefined"),
	cmdlinechanged = module.autocmd_base("cmdlinechanged"),
	cmdlineenter = module.autocmd_base("cmdlineenter"),
	cmdlineleave = module.autocmd_base("cmdlineleave"),
	cmdwinenter = module.autocmd_base("cmdwinenter"),
	cmdwinleave = module.autocmd_base("cmdwinleave"),
	colorscheme = module.autocmd_base("colorscheme"),
	colorschemepre = module.autocmd_base("colorschemepre"),
	completechanged = module.autocmd_base("completechanged"),
	completedonepre = module.autocmd_base("completedonepre"),
	completedone = module.autocmd_base("completedone"),
	cursorhold = module.autocmd_base("cursorhold"),
	cursorholdi = module.autocmd_base("cursorholdi"),
	cursormoved = module.autocmd_base("cursormoved"),
	cursormovedi = module.autocmd_base("cursormovedi"),
	diffupdated = module.autocmd_base("diffupdated"),
	dirchanged = module.autocmd_base("dirchanged"),
	fileappendcmd = module.autocmd_base("fileappendcmd"),
	fileappendpost = module.autocmd_base("fileappendpost"),
	fileappendpre = module.autocmd_base("fileappendpre"),
	filechangedro = module.autocmd_base("filechangedro"),
	exitpre = module.autocmd_base("exitpre"),
	filechangedshell = module.autocmd_base("filechangedshell"),
	filechangedshellpost = module.autocmd_base("filechangedshellpost"),
	filereadcmd = module.autocmd_base("filereadcmd"),
	filereadpost = module.autocmd_base("filereadpost"),
	filereadpre = module.autocmd_base("filereadpre"),
	filetype = module.autocmd_base("filetype"),
	filewritecmd = module.autocmd_base("filewritecmd"),
	filewritepost = module.autocmd_base("filewritepost"),
	filewritepre = module.autocmd_base("filewritepre"),
	filterreadpost = module.autocmd_base("filterreadpost"),
	filterreadpre = module.autocmd_base("filterreadpre"),
	filterwritepost = module.autocmd_base("filterwritepost"),
	filterwritepre = module.autocmd_base("filterwritepre"),
	focusgained = module.autocmd_base("focusgained"),
	focuslost = module.autocmd_base("focuslost"),
	funcundefined = module.autocmd_base("funcundefined"),
	uienter = module.autocmd_base("uienter"),
	uileave = module.autocmd_base("uileave"),
	insertchange = module.autocmd_base("insertchange"),
	insertcharpre = module.autocmd_base("insertcharpre"),
	textyankpost = module.autocmd_base("textyankpost"),
	insertenter = module.autocmd_base("insertenter"),
	insertleavepre = module.autocmd_base("insertleavepre"),
	insertleave = module.autocmd_base("insertleave"),
	menupopup = module.autocmd_base("menupopup"),
	optionset = module.autocmd_base("optionset"),
	quickfixcmdpre = module.autocmd_base("quickfixcmdpre"),
	quickfixcmdpost = module.autocmd_base("quickfixcmdpost"),
	quitpre = module.autocmd_base("quitpre"),
	remotereply = module.autocmd_base("remotereply"),
	sessionloadpost = module.autocmd_base("sessionloadpost"),
	shellcmdpost = module.autocmd_base("shellcmdpost"),
	signal = module.autocmd_base("signal"),
	shellfilterpost = module.autocmd_base("shellfilterpost"),
	sourcepre = module.autocmd_base("sourcepre"),
	sourcepost = module.autocmd_base("sourcepost"),
	sourcecmd = module.autocmd_base("sourcecmd"),
	spellfilemissing = module.autocmd_base("spellfilemissing"),
	stdinreadpost = module.autocmd_base("stdinreadpost"),
	stdinreadpre = module.autocmd_base("stdinreadpre"),
	swapexists = module.autocmd_base("swapexists"),
	syntax = module.autocmd_base("syntax"),
	tabenter = module.autocmd_base("tabenter"),
	tableave = module.autocmd_base("tableave"),
	tabnew = module.autocmd_base("tabnew"),
	tabnewentered = module.autocmd_base("tabnewentered"),
	tabclosed = module.autocmd_base("tabclosed"),
	termopen = module.autocmd_base("termopen"),
	termenter = module.autocmd_base("termenter"),
	termleave = module.autocmd_base("termleave"),
	termclose = module.autocmd_base("termclose"),
	termresponse = module.autocmd_base("termresponse"),
	textchanged = module.autocmd_base("textchanged"),
	textchangedi = module.autocmd_base("textchangedi"),
	textchangedp = module.autocmd_base("textchangedp"),
	user = module.autocmd_base("user"),
	usergettingbored = module.autocmd_base("usergettingbored"),
	vimenter = module.autocmd_base("vimenter"),
	vimleave = module.autocmd_base("vimleave"),
	vimleavepre = module.autocmd_base("vimleavepre"),
	vimresized = module.autocmd_base("vimresized"),
	vimresume = module.autocmd_base("vimresume"),
	vimsuspend = module.autocmd_base("vimsuspend"),
	winclosed = module.autocmd_base("winclosed"),
	winenter = module.autocmd_base("winenter"),
	winleave = module.autocmd_base("winleave"),
	winnew = module.autocmd_base("winnew"),
	winscrolled = module.autocmd_base("winscrolled")

}

return module
