name: "Nix-based Integration Test"

# This workflow attempts to install Neorg with a kickstart config on all major OSes.
# Uses Nix for reproducibility.

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  integration-test:
    runs-on: ${{ matrix.os.host }}
    strategy:
      matrix:
        os:
          - host: ubuntu-latest
          # - host: windows-2019
          - host: macos-26-intel # x86_64
          - host: macos-latest # aarch64
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v17
      - name: Run Checks
        run: nix run .#integration-test
