name: Run tests
on:
  pull_request: ~
  push:
    branches:
      - main

jobs:
  test:
    name: Tests
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install MSVC Compiler Toolchain
        uses: ilammy/msvc-dev-cmd@v1
        if: endsWith(matrix.job.target, '-msvc')

      - name: Setup Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: stable

      - name: Install Lux
        uses: lumen-oss/gh-actions-lux@v1
        with:
          version: 0.26.4

      - name: Run tests
        run: |
          lx --no-luarc --nvim --lua-version 5.1 test
